items = [ "Wallet", "Phone", "Keys" ]
print(items)
items.sort()
print(items)
print(items[0])
print(items[1:3])
print(items[-1])
print(str(items.index("Keys")))
items.append("Tablet")
print(items)
items.insert(1, "Glasses")
print(items)
items.remove("Phone")
print(items)
items.reverse()
print(items)