#   HW: Moving Agents
#   Author: Dylan Emerson
#   File: Constants.py

from Vector import *

# Screen constants
BACKGROUND_COLOR = (100, 149, 237)
DISPLAY_WIDTH = 800
DISPLAY_HEIGHT = 600
SCREEN_SIZE = Vector(DISPLAY_WIDTH, DISPLAY_HEIGHT)
FRAME_RATE = 60

# World constants
WORLD_MAX_SHEEP = 10

# Dog constants
DOG_COLOR = (246, 240, 136)
DOG_SIZE = 10
DOG_SPEED = 1.5
DOG_DIRECTION_WEIGHT = 0.8

# Sheep constants
SHEEP_COLOR = (89, 205, 144)
SHEEP_SIZE = 10
SHEEP_SPEED = 1
SHEEP_FLEE_RANGE = 100
SHEEP_TICKS_TO_WAIT = 800
SHEEP_ROTATION_SCALAR = 0.1

# Debug constants
DEBUG_VELOCITY_COLOR = (0, 0, 255)
DEBUG_VELOCITY_LENGTH = 15
DEBUG_SEEKFLEE_COLOR = (255, 0, 0)