#   HW: Moving Agents
#   Author: Dylan Emerson
#   File: Constants.py

from Vector import *

# Screen constants
BACKGROUND_COLOR = (100, 149, 237)
DISPLAY_WIDTH = 800
DISPLAY_HEIGHT = 600
SCREEN_SIZE = Vector(DISPLAY_WIDTH, DISPLAY_HEIGHT)
FRAME_RATE = 60

# World constants
WORLD_MAX_SHEEP = 10
WORLD_MIN_DISTANCE = 25
WORLD_BOUNDARY_FORCE = 2

# Agent constants
AGENT_WIDTH = 16
AGENT_HEIGHT = 32

# Dog constants
DOG_COLOR = (246, 240, 136)
DOG_SPEED = 2
DOG_SEEK_WEIGHT = 0.9

# Sheep constants
SHEEP_COLOR = (89, 205, 144)
SHEEP_SPEED = 1.5
SHEEP_FLEE_RANGE = 100
SHEEP_TICKS_TO_WAIT = 800
SHEEP_ROTATION_SCALAR = 0.1
SHEEP_WANDER_WEIGHT = 0.4
SHEEP_FLEE_WEIGHT = 0.7

# Debug constants
DEBUG_VELOCITY_COLOR = (0, 0, 255)
DEBUG_VELOCITY_LENGTH = 25
DEBUG_SEEKFLEE_COLOR = (255, 0, 0)